CREATE TABLE IF NOT EXISTS shortcuts (
    id TEXT NOT NULL PRIMARY KEY,
    url TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    expires_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visits (
    id INTEGER NOT NULL PRIMARY KEY,
    shortcut_id TEXT NOT NULL,
    date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    referer TEXT NOT NULL,
    country TEXT,
    FOREIGN KEY (shortcut_id) REFERENCES shortcuts (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS banned_domains (
    id INTEGER NOT NULL PRIMARY KEY,
    domain TEXT NOT NULL UNIQUE,
    reason TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);