PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE shortcuts (
    id TEXT NOT NULL PRIMARY KEY,
    url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    password_hash TEXT NOT NULL
);

CREATE TABLE visits (
    id INTEGER NOT NULL PRIMARY KEY,
    shortcut_id TEXT NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    referer TEXT NOT NULL,
    FOREIGN KEY (shortcut_id) REFERENCES shortcuts (id) ON DELETE CASCADE
);
