CREATE TABLE IF NOT EXISTS shortcuts (
    id TEXT NOT NULL PRIMARY KEY,
    url TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visits (
    id INTEGER NOT NULL PRIMARY KEY,
    shortcut_id TEXT NOT NULL,
    date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    referer TEXT NOT NULL,
    FOREIGN KEY (shortcut_id) REFERENCES shortcuts (id) ON DELETE CASCADE
);
